### ISSUE TITLE
Updates/corrections for appstore release

### ISSUE THREAD

**Issue by RealRancor** [v1r0x/polls#1]
Hi,

there are currently two issues where at least one of them make the app not install-able via the oC internal appstore:

1. The appinfo/info.xml should contain the ``<ocsid>174671</ocsid>`` metadata
2. The archive at the appstore (https://apps.owncloud.com/content/show.php/Polls?content=174671) containing a folder named polls-0.6.0. This makes the app not install-able as a:

> Archive does not contain a directory named polls

is shown when trying to enable the app. The appstore/ownCloud is expecting a folder just called "polls". Some instructions how to release such a version via github where posted here: https://github.com/owncloud/core/issues/18116#issuecomment-129445478

**Comment by v1r0x** [comment]
Thanks for your contribution

1. Thought this would break it and is an old tag^^'

**Comment by v1r0x** [comment]
@RealRancor Could you please test again and close the issue if it works (or report if the problem still exists, of course)

**Comment by RealRancor** [comment]
Works now to install the app from within oC. Thanks! :+1:

**Comment by v1r0x** [comment]
Great! Thanks again for your help! :)
