### ISSUE TITLE
Anonymous has no effect for polls admin

### ISSUE THREAD

**Issue by scroom** [v1r0x/polls#100]
If I use the Anonymous-mode I've expected that I, as the one who created the poll, couldn't see who voted for what. But the opposite is the case: I can see who voted for what.

Maybe it would be a good idea to have an advanced Anonymous-mode. So no-one could be blamed for its choices.

**Comment by v1r0x** [comment]
The idea behind anonymous polls was to have to ability that no user could see the other's names (e.g. for exam schedules), but yes, a completely anonymous poll would be a good option, too.
I'll add it to the milestone for the next release.
