### ISSUE TITLE
No difference between hidden and open poll?

### ISSUE THREAD

**Issue by scroom** [v1r0x/polls#101]
In fact I tried to find out what the difference between hidden and open polls are, but have found none.

For both cases users can access the poll if they know the exact link and registered users can see both of them as well (there is as well no difference to the case registered users)

**Comment by v1r0x** [comment]
The difference should be that hidden polls are only visible for the user who created it or participated. Other users should not see them on the summary page.

Do registered users see hidden polls on their summary page even if they are not the owner and haven't participated in it?

**Comment by scroom** [comment]
Yes registered users can see hidden polls on their summary page even if they are not the owner and haven't participated.

**Comment by v1r0x** [comment]
Seems to be a bug, is on the list for the next release.
