### ISSUE TITLE
app not working

### ISSUE THREAD

**Issue by satishsingh5816** [v1r0x/polls#107]
nothing selected
click on cells to turn them green owncloud

**Comment by satishsingh5816** [comment]
this error

https://drive.google.com/file/d/0B4AaV7HNky5uYm1NVW5XVHJZekE/view?usp=sharing

please help me

**Comment by v1r0x** [comment]
Sorry for my late reply. Still have this error?
It looks like you have not selected a date and time in the calendar on the right side. You need to add dates and then you have several rectangles with red background and a cross sign. If you click on them they turn green and get a checkmark icon. Then you should be able to create a poll.
