### ISSUE TITLE
Translation - FR or IT

### ISSUE THREAD

**Issue by Ludovicis** [v1r0x/polls#108]
Hello, 

Thanks v1r0x for this application.

As this problem : https://github.com/v1r0x/polls/issues/48

I want translate your application in french but i can't...

I have also create fr.json and fr.php but this modification don't work.

[fr.php.txt](https://github.com/v1r0x/polls/files/631452/fr.php.txt)

[fr.json.txt](https://github.com/v1r0x/polls/files/631449/fr.json.txt)

Can you help me please ?

Thanks,

**Comment by v1r0x** [comment]
Hi @Ludovicis ,
thanks for helping translate this app. Really appreciate it!
Here in github they are named `fr.<format>.txt`. You have to remove the `.txt`.
But you could create a pull request with these two new files and then we could add french as another language :)

**Comment by Ludovicis** [comment]
Hi v1r0x,

Have you seen my pull request ?
Can you update your poll app, please ?
Thanks,

**Comment by v1r0x** [comment]
Hi Ludovicis,

Yes, I've seen it. Thanks!

There are two things keeping me from merging it.
1. It is based on a very old branch and your files are not part of the PR, they are only present in your comment
2. I'm very busy at the moment. I hope I have some free time after christmas.

It's on my list for the next release :smiley:

**Comment by Ludovicis** [comment]
Hi v1r0x, 

Maybe someone can help you to create the next release ?
I am not developper but if i can help.

Thanks,
