### ISSUE TITLE
Polls is not in the Nextcloud-App-Store

### ISSUE THREAD

**Issue by scroom** [v1r0x/polls#113]
As described above. At the moment it is not possible to install polls directly out of the Nexcloud-App-Store. Here are the NC-instructions how to publish an app at the App-Store:

https://nextcloudappstore.readthedocs.io/en/latest/developer.html#publishing-apps-on-the-app-store

**Comment by happyreacer** [comment]
how looks it?

**Comment by happyreacer** [comment]
@v1r0x is it a problem?

**Comment by v1r0x** [comment]
Sorry for the late response. My plan was to publish the app to the nc appstore with the next release. I'm currently very busy with my job, so I don't know when I can work on the open issues. But soon :wink:

**Comment by v1r0x** [comment]
This one will be fixed as soon as #123 and #124 are merged.

**Comment by poVoq** [comment]
Any update on this? Would be great to have it easily available in NC12 :)

**Comment by joergmschulz** [comment]
@poVoq If you are able to, it would be good to pick up and repair the current issues. You'll detect a badly done fix from myself, and an open issue with Safari. Without these fixes, polls doesn't work correctly on NC12.

**Comment by v1r0x** [comment]
Totally forgot about the review of @joergmschulz PR! Sorry about that. Was very busy the last weeks. I do it in the next days. I promise! 😉

**Comment by v1r0x** [comment]
Finally uploaded....Thanks for all contributions!

**Comment by F1iX** [comment]
Unfortunately I cannot install/find Polls from the Nextcloud 13.1 app store right now. Do we need to re-open the issue?

**Comment by happyreacer** [comment]
@F1iX  see here https://apps.nextcloud.com/apps/polls

**Comment by F1iX** [comment]
@happyreacer thanks for your answer. Indeed the app can be found in the global online app store, but is not visible in both of my nextcloud instances...

**Comment by poVoq** [comment]
It is there under tools. Scroll down the left side category list.

**Comment by F1iX** [comment]
@poVoq thanks, you're right :-)
For some reason I did not see it in the list, but searching for polls in the Tools-tab did the job.
