### ISSUE TITLE
Text polls: handle duplicate entries

### ISSUE THREAD

**Issue by joergmschulz** [v1r0x/polls#114]
When, in text polls, an entry is duplicate, a user who selects one of the duplicates automatically selects the other instance as well.
Example:
create a 'bring stuff for the coffee invitation' poll.
Enter things like

```
cake
koffee
tea
sugar
tea
```

You'll see that `tea` is duplicate. 
The intended effect is that two users can decide to bring tea independently - but in reality, both entries can only be selected together.
I know - the workaround would be to create choices like (black tea|green tea).

I suggest we either prevent duplicate entries to be created  (like for the date polls) or cater for duplicate entries.

**Comment by v1r0x** [comment]
Thanks for your report. I'll look into it.
