### ISSUE TITLE
Nextcloud 11.0.2 issues, fix inside

### ISSUE THREAD

**Issue by bogie** [v1r0x/polls#118]
I am currently on Nextcloud 11.0.2, php 7.1.3 and forked cdb7c4c74bc822c6536745a964287caca0f81854 creating polls works without any issues however when viewing the created poll there are several errors showing.

I started off with var_dump($dates) in goto.tmpl showing an empty array, I traced the error back to your use of getType() === '0' as getType() returns an integer: (0 === '0')  will return false, as it should!

This fixed all my issues and I can now create and vote in polls in Nextcloud 11.0.2

**Comment by v1r0x** [comment]
Thanks for your report! Looks like the changes something in NC. I had to check `getType() === '0'` because `getType()` returned an integer. You can create a PR if you want. Then I can merge your fix.

**Comment by bogie** [comment]
'0' is not an integer, in php it is a string! Therefore it depends what type getType() returns.

In nc 11.0.2 it returns an integer, therefore integer === string will return false!
What does it return in oc? If it returns a string, then do you want to be compatible to oc?
Do you need to do a identical type comparison? If oc returns a string and nc returns an integer then maybe getType() == '0' is okay? Since it will return true in both cases!

**Comment by v1r0x** [comment]
> '0' is not an integer, in php it is a string! Therefore it depends what type getType() returns.

Sorry, I meant that `getType()` returned a string instead of an integer. Thus I had to compare it to `'0'` instead of `0`.

> In nc 11.0.2 it returns an integer, therefore integer === string will return false!
> What does it return in oc? If it returns a string, then do you want to be compatible to oc?
> Do you need to do a identical type comparison? If oc returns a string and nc returns an integer then maybe getType() == '0' is okay? Since it will return true in both cases!

In oc it definitely returns a string. I think in nc 10 it's string as well. I switched from `==` to `===` because the oc app check tool recommended it. But if nc11 returns an integer and nc10/oc returns a string I'd go with `==`

**Comment by bogie** [comment]
I believe that nc finally takes the type from the database. I will prepare a PR with == then to ensure backwards compatibility.

**Comment by v1r0x** [comment]
Fixed by #119
