### ISSUE TITLE
polls not compatible with NC12

### ISSUE THREAD

**Issue by joergmschulz** [v1r0x/polls#122]
### Steps to reproduce
0. _log in with a user from LDAP._ This error does NOT come up with 'normal' users.
1. change max version in appinfo to 12
2. php occ app:enable polls
3. open polls

### Expected behaviour
polls should open

### Actual behaviour
the app crashes with following info:
- screen: complains about an internal error.
- nextcloud log doesn't contain anything relevant
- browser console contains: 
[Error] ReferenceError: Can't find variable: oc_appconfig
	(anonyme Funktion) (merged-share-backend.js:24)
	Globaler Code (merged-share-backend.js:80)
[Error] TypeError: undefined is not an object (evaluating 'link.substring')
	filePath (merged-template-prepend.js:1349)
	Globaler Code (viewer.js:15:151)
[Error] TypeError: undefined is not an object (evaluating 'oc_config.version.match')
	(anonyme Funktion) (ojsxc.js:275)
	j (core.js:2:26931)
	fireWith (core.js:2:27740)
	ready (core.js:2:29544)
	I (core.js:2:29729)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (purify.min.js.map, line 0)

### Server configuration
**Operating system**: Linux yarra 4.9.0-2-686-pae #1 SMP Debian 4.9.13-1 (2017-02-27) i686

**Web server:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.22

**PHP version:** 7.0.16-3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, json, ldap, exif, memcache, msgpack, mysqli, odbc, pdo_mysql, PDO_ODBC, pdo_pgsql, pgsql, Phar, posix, radius, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache

**Nextcloud version:** 12.0 beta 1 - 12.0.0.16

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated
**Where did you install Nextcloud from:** 
latest tar
**Signing status:**
<details>
	<summary>Signing status</summary>

```
{
    "direct_menu": {
        "EXCEPTION": {
            "class": "OC\\IntegrityCheck\\Exceptions\\InvalidSignatureException",
            "message": "Certificate is not valid."
        }
    }
}
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.1
 - admin_audit: 1.2.0
 - apporder: 0.3.3
 - calendar: 1.5.2
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.1.3
 - encryption: 1.6.0
 - external: 1
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_external: 1.3.0
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.0.2
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - nextcloud_announcements: 1.1
 - notes: 2.2.0
 - notifications: 2.0.0
 - ojsxc: 3.2.0-beta.3
 - password_policy: 1.2.2
 - polls: 0.7.2.1
 - provisioning_api: 1.2.0
 - rainloop: 4.28.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - spreed: 2.0.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.0
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0

Disabled:
 - direct_menu
 - files_trashbin
 - files_versions
 - spreedme
 - user_external
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "updatechecker": false,
    "instanceid": "ocdcwtltlwy2",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "waitaki.fritz.box",
        "192.168.178.41",
        "yarra.fritz.box"
    ],
    "datadirectory": "\/var\/www\/nextcloud\/data",
    "overwrite.cli.url": "http:\/\/yarra.fritz.box\/nextcloud",
    "dbtype": "mysql",
    "version": "12.0.0.16",
    "dbname": "oc",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_from_address": "joerg.schulz",
    "mail_smtpmode": "smtp",
    "mail_domain": "elternserver.de",
    "ldapIgnoreNamingRules": false,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "elternserver.de",
    "mail_smtpport": "25",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "beta",
    "has_internet_connection": true,
    "updater.server.url": "https:\/\/updates.nextcloud.org\/updater_server\/",
    "maintenance": false,
    "defaultapp": "announcementcenter",
    "0": "files",
    "theme": "",
    "loglevel": 0,
    "appstore.experimental.enabled": true,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "singleuser": false,
    "mail_smtpsecure": "tls",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** 
LDAP

### Client configuration
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30

**Comment by v1r0x** [comment]
The error looks weird. Look into it. Thanks for your reports!

**Comment by joergmschulz** [comment]
maybe a look at difficulties other app developers (ojsxc, audioplayer) have with NC 12 - links inside could help you: https://help.nextcloud.com/t/nc12-breaking-changes/11798

**Comment by v1r0x** [comment]
Based on your comment in #123 you can now enable/use the polls app iff you do not login via ldap? So it works for local users?

**Comment by joergmschulz** [comment]
Exactly. For local users, it works, for LDAP it doesn’t.

**Comment by v1r0x** [comment]
Is there any new error message? Unfortunately I don't have a ldap-server for my testing VMs. Maybe I could try to use the ldap connection of my production system.

**Comment by joergmschulz** [comment]
No, it is the error message I’ve posted.
So bad my NC12 test installations are only local/virtualbox. One of these days, I might have a test environment for NC12 up and running soon - but this might take a week or so.

**Comment by v1r0x** [comment]
I added my production server's ldap settings to my local virtualbox nc 12 instance and the polls app works as expected. Maybe you have to update the ldap addon? Or anything else is not compatible. Could you try to setup a new nc 12 instance and only enable ldap and polls (if you did not already)?

**Comment by joergmschulz** [comment]
I have good news for everybody: I disabled polls app, dropped all my oc_polls* table from the database and reenabled polls app. Now the app works. Will continue to test.
This could mean that either the upgrade to the new version failed to modify the database structure or that my database has been corrupt somehow. I failed to create a snapshot before this action, so it's unclear how to reproduce.

**Comment by v1r0x** [comment]
Haven't tested it with restricted polls. Maybe something has changed there. Will test it with a restricted poll.

**Comment by v1r0x** [comment]
Looks like it is possible to search for ldap groups, but calling `getUserGroups()` on ldap users doesn't get the user's ldap groups...

**Comment by joergmschulz** [comment]
see PR #127 / in my env, this fixes the group issue. But, the fix needs some review and hopefully a change in template.
