### ISSUE TITLE
Text based polls editing does not show texts

### ISSUE THREAD

**Issue by danielepercivaldi** [v1r0x/polls#23]
If you define a poll like this:
![cattura](https://cloud.githubusercontent.com/assets/8720648/13731795/adc753a8-e972-11e5-85d8-0400c56584b8.JPG)

When you edit it you cannot see its own texts:
![cattura](https://cloud.githubusercontent.com/assets/8720648/13731799/d5c9de34-e972-11e5-9a33-af1c5707d2a3.JPG)

**Comment by v1r0x** [comment]
Please test #29
