### ISSUE TITLE
Internal server error happens when voting

### ISSUE THREAD

**Issue by danielepercivaldi** [v1r0x/polls#24]
![cattura](https://cloud.githubusercontent.com/assets/8720648/13731837/6ef75640-e973-11e5-9eb7-a7dcff81164d.JPG)

**Comment by v1r0x** [comment]
Just for the record: This only happens with text polls?

**Comment by danielepercivaldi** [comment]
Yes

**Comment by v1r0x** [comment]
Ok, I'll do some more testing with text polls.

**Comment by v1r0x** [comment]
Please test #27, hopefully it works now.
