### ISSUE TITLE
Cannot understand how voting procedure works

### ISSUE THREAD

**Issue by danielepercivaldi** [v1r0x/polls#25]
How the poll appears:
![cattura](https://cloud.githubusercontent.com/assets/8720648/13731849/fe32de38-e973-11e5-9050-deee1e4b9e7e.JPG)
If I press on the "yellow area" it becomes:
![cattura](https://cloud.githubusercontent.com/assets/8720648/13731859/26759a66-e974-11e5-94d3-13ad9645fd2e.JPG)
and again
![cattura](https://cloud.githubusercontent.com/assets/8720648/13731868/5839fc4a-e974-11e5-8108-44c306b6d2cd.JPG)
If I continue 
![cattura](https://cloud.githubusercontent.com/assets/8720648/13731874/8d7691de-e974-11e5-9553-d13cba1cf112.JPG)

Please, explain to me. Is it rigth?

**Comment by v1r0x** [comment]
The colored area on the left of the vote cells is a "toggle-all" cell. It should turn all cells to the color of the "toggle-all" color. This cell should work as all other cells.

But you are right. There should be some explanation what it does. Maybe @jancborchardt has an idea? (Sorry for mention you ;))

**Comment by danielepercivaldi** [comment]
Ok, I see: it works only for event polls.
In text polls toggle-all does not work and you cannot vote single item (the pointer change but when you clic nothing happens).

**Comment by v1r0x** [comment]
This should be fixed in #27 as well.

**Comment by jancborchardt** [comment]
@v1r0x just as driveby feedback: There’s a bit too much bold in the interface. :) And also the dark blue should not be used anywhere except primary action buttons.
