### ISSUE TITLE
clicking on the app-button ends on a blank page

### ISSUE THREAD

**Issue by Liwindo** [v1r0x/polls#3]
### Steps to reproduce
1. Have the old polls-app installed
2. Upgrade to the new polls-app
3. activate the app
4. click on the app button

### Expected behaviour
The app works fine

### Actual behaviour
A blank page appears

### Server configuration
**Operating system**: Ubuntu 14.04.4

**Web server:** apache with nginx proxy

**Database:** mysql 5.5.47-0ubuntu0.14.04.1

**PHP version:** 7.0.3

**ownCloud version:** 8.2.2

```
### Logs
#### ownCloud log (data/owncloud.log)
```
TypeError: Argument 2 passed to OCP\AppFramework\Db\Mapper::findEntities() must be of the type array, null given, called in /var/www/vhosts/domain.tld/owncloud/apps/polls/db/eventmapper.php on line 47 at /var/www/vhosts/domain.tld/owncloud/lib/public/appframework/db/mapper.php#318 

---
Additionally I tried the downloaded source code (V. 0.6.9.1). With it the folder-rights-problem does not occur but the blank page problem still exists. Obviously are the folder rights in the 0.6.9 release not set correct.

**Comment by v1r0x** [comment]
I don't know if PHP7 is a problem. I'm currently trying to set up a VM with PHP7 to check if I have the same problem. Do you have a oc instance with an older php version? You said you tried it on several systems. Are there any differences between your systems?

> Additionally I tried the downloaded source code (V. 0.6.9.1). With it the folder-rights-problem does not occur but the blank page problem still exists. Obviously are the folder rights in the 0.6.9 release not set correct.

You could also try the current master. I made some small fixes (unrelated to you error, but maybe it works).

**Comment by Liwindo** [comment]
Indeed, PHP 7 is the problem. With 5.6.18 it works fine.

**Comment by v1r0x** [comment]
Can confirm that. Same problem on PHP7 for me. I'll look into it.

**Comment by v1r0x** [comment]
@Liwindo Could you please test the PR #4 with your PHP7 instance?

**Comment by MarPiRK** [comment]
I had the same situation and it works for me (CentOS 7, PHP-FPM 7.0.3 from remi repo).

**Comment by RealRancor** [comment]
@Liwindo @MarPiRK Btw. you guys should be aware that oC 8.2.2 is not compatible with PHP 7. Watch out for oC 8.2.3 to get compatibility with that version of PHP.

**Comment by v1r0x** [comment]
> UPDATE: I don't see blank page, but after I add new poll I see blank page. Poll is added though. The same is for Vote.

Sorry, totally forgot about it! There was a bug in core which returned a wrong http status code for the redirect response I use in this case. I'll try to find a workaround or, if this doesn't work add a note to the readme file (#5).
If you want to fix it, see [this PR](https://github.com/owncloud/core/pull/22497) for the lines you have to edit.

> @Liwindo @MarPiRK Btw. you guys should be aware that oC 8.2.2 is not compatible with PHP 7. Watch out for oC 8.2.3 to get compatibility with that version of PHP.

I thought 8.2 is already compatible with PHP 7. At least that's what I read while trying to setup a VM with PHP7.

**Comment by RealRancor** [comment]
> I thought 8.2 is already compatible with PHP 7. At least that's what I read while trying to setup a VM with PHP7.

Unfurtunately not. The SabreDAV lib shipped with oC 8.2.2 and earlier is not PHP 7 compatible:

https://github.com/owncloud/core/issues/21914, https://github.com/owncloud/core/pull/21938

**Comment by MarPiRK** [comment]
@v1r0x Nice, with this fix everything works.
@RealRancor Basing on https://owncloud.org/blog/php-7-is-here-and-owncloud-is-ready/ it looks like core is compatible in general – only Calendar and Contacts apps (which utilize SabreDAV from core) have some issues.

**Comment by RealRancor** [comment]
@MarPiRK Everything what is SabreDAV (WebDAV, CalDAV, CardDAV) might have or has issues with PHP7.

**Comment by MarPiRK** [comment]
@RealRancor Good to know

**Comment by Liwindo** [comment]
I can confirm that it works now. But is it normal that the background of a created polls gets white when I put the mouse curser on it? Have a look: http://www.directupload.net/file/d/4276/veex8tm4_png.htm

**Comment by v1r0x** [comment]
Yes and no. Didn't know why it has been this way, but found the problem ;)
