### ISSUE TITLE
Voting not possible in chromium 48

### ISSUE THREAD

**Issue by dekuenstle** [v1r0x/polls#30]
Clicking on the fields resulted in no feedback in chromium 48

**Comment by v1r0x** [comment]
Any errors in the js console? (`Ctrl+Shift+J` I think).

**Comment by dekuenstle** [comment]
Ah, yes, sorry:
The ES6 feature  default parameter which chrome only supports in 49+ is the problem here. 
If you prefer using modern JS (which is a good idea), think about using a converter like [babel](https://babeljs.io/) and shims while the browser support is that weak (esp IE). 

> function selectItem(cell, cl='') {

PS: `Ctrl+Shift+i` ;)

**Comment by v1r0x** [comment]
I already fixed this in our OC, but forgot to pull. Should work now ;)

**Comment by dekuenstle** [comment]
Works :)) Thank you!
