### ISSUE TITLE
Fast clicking produced wrong graphical feedback

### ISSUE THREAD

**Issue by dekuenstle** [v1r0x/polls#31]
If you fast double/trible click on a field, the color just switches to the next one instead of the one after (or 2 after). The numbers sometimes did very weird things and did not represent the correct data shown with the field colors. For example there was a green 5 for a poll with only 3 voters.

**Comment by v1r0x** [comment]
Already have a lot of bugs in the 0.7 milestone. So, rather a fix for 0.7.x

**Comment by v1r0x** [comment]
@mcorteel did some code cleanup (and huge UI changes). Couldn't reproduce it on my test machine. Could you @dekuenstle test if it still happens?

**Comment by mcorteel** [comment]
Yes, my changes from #52 should fix that.
