### ISSUE TITLE
Poll initialization

### ISSUE THREAD

**Issue by danielepercivaldi** [v1r0x/polls#36]
When you enter a poll the first time and never voted:
![cattura](https://cloud.githubusercontent.com/assets/8720648/13761360/55eabc44-ea38-11e5-8d19-f6d42a04c4c9.JPG)
I think it should instead be:
![cattura](https://cloud.githubusercontent.com/assets/8720648/13761400/a7303a34-ea38-11e5-86a0-37caf5cd8e87.JPG)
because if you vote a single item (-1 ?!?):
![cattura](https://cloud.githubusercontent.com/assets/8720648/13761435/dea367ca-ea38-11e5-88de-a1a1d2db1974.JPG)

**Comment by v1r0x** [comment]
No, the white cells are intended. The "-1" of course not ;)
