### ISSUE TITLE
Disabled items no more present in editing mode

### ISSUE THREAD

**Issue by danielepercivaldi** [v1r0x/polls#37]
I defined the following text poll (4 items: 2 enabled, 2 disabled):
![cattura](https://cloud.githubusercontent.com/assets/8720648/13761543/8d007024-ea39-11e5-8429-18ab8f711b48.JPG)
I saved it and then entered in editing. There are no more the disabled items:
![cattura](https://cloud.githubusercontent.com/assets/8720648/13761587/d57db4ec-ea39-11e5-9dae-8d3a01a78ec6.JPG)

**Comment by v1r0x** [comment]
Yes, only previous selected items are present in editing mode. Expect for items where only some of a row are selected.
