### ISSUE TITLE
Multiple errors and problems

### ISSUE THREAD

**Issue by darootler** [v1r0x/polls#49]
Hi,

thank you for developing this app. It's very great and i love it.

Actually it seems that there are multiple problems, here are some error messages:

{PHP} Undefined variable: poll_id at /var/www/owncloud/apps/polls/templates/goto.tmpl.php#75 --> On poll creation

PHP Fatal error:  Call to a member function t() on a non-object in /var/www/owncloud/apps/polls/controller/pagecontroller.php on line 119 --> On poll creation

{PHP} Trying to get property of non-object at /var/www/owncloud/apps/polls/controller/pagecontroller.php#288 --> On poll creation

{PHP} Undefined variable: l at /var/www/owncloud/apps/polls/controller/pagecontroller.php#119 --> On public vote, followed by a HTTP 500

Let me know if you need more information.

Regards

Richard

**Comment by v1r0x** [comment]
Thanks for your kind words and reporting the errors!
Could you give some more information about your system? What OC, PHP and polls version do you use?
I think the HTTP 500 is caused by a pre-9.0 oc bug. A solution can be found in the readme or on the apps.owncloud.com page.

**Comment by darootler** [comment]
Hi,

here is some information:

OS: Ubuntu 14.04.4 LTS
OC: 9.0.1
PHP: 5.5.9
polls: 0.7.0

It seems that the bug is already fixed in oc 9.0.1, i just reviewed the installed php files.

Regards
Richard

**Comment by darootler** [comment]
Hi,

i am able to create a public poll on my OC installation and send you the link to it. Just if this would help you.

Regards
Richard

**Comment by v1r0x** [comment]
That would be nice. Unfortunately I don't have that much time for OC atm, especially because I destroyed (sort of) my laptop. I hope I'll find some time this weekend.

**Comment by darootler** [comment]
Hi,

i see. Here is the test poll:

https://server.marschik.biz/owncloud/index.php/apps/polls/goto/JQGBLGkTjvoJDjW3

On creation i got this error:

{PHP} Trying to get property of non-object at /var/www/owncloud/apps/polls/controller/pagecontroller

If i just visit the poll i get this error:

{PHP} Undefined variable: poll_id at /var/www/owncloud/apps/polls/templates/goto.tmpl.php#75

If i submit a vote i get this error:

{PHP} Undefined variable: l at /var/www/owncloud/apps/polls/controller/pagecontroller.php#119
 
Followed by a HTTP 500

Regards
Richard
