### ISSUE TITLE
Just some groups and persons available to choose

### ISSUE THREAD

**Issue by scroom** [v1r0x/polls#50]
Hi,

thanks for your great app! Just installed Polls in our schools ownCloud instance. But then I've realized that only a few groups are shown if I click on choose (it seems that these are the groups I'm member of) and as well only some random users. We're using a LDAP backend for user authentication.
For our usecase it would be great if one could choose a group (a class or course) and create a poll for them. Normally everyone can see every group (and share for example files with them).

**Comment by v1r0x** [comment]
It is intended that you only see groups you are a member of. Thought there wouldn't be a case where you want to create polls for other groups.
Do the "random users" have something in common? We use LDAP as well and don't have any problems with it. Maybe some group or admin connection between those users.
I hope I have some time this weekend to switch from *only user groups* to *all groups*

**Comment by scroom** [comment]
In fact for us it would be the best to have a search field (similar to the search field in ownCloud itself to share files etc.) out of which one could add groups or persons to the poll.
It would prevent the problem that only random users are loaded in the user field (around 50 but we are having more than 900 users)

**Comment by v1r0x** [comment]
I'll think about it and try to find a proper solution.

**Comment by v1r0x** [comment]
@scroom It's been a while, but thanks to @bodo1987 the user/group pick list has been cleaned up. Does your problem still exist or has it been fixed with the new version? (Check out current master to see the result)

**Comment by scroom** [comment]
Hey!

Sorry for responding so late. My problem is solved partially. No I can search for every registered user. But still I can just choose the groups I'm in. Would be great for our use case (a school) if we could register poll for classes (teachers are not part of the class und courses groups).

**Comment by v1r0x** [comment]
So teachers are in different groups and no admins?
I think your use case is a very special one, thus I think it would be _wrong_ to enable this feature for all users. Nevertheless it would be good to find a solution for your particular problem.
I think we shouldn't expose all groups to all users or only expose them depending on the following admin settings:
- Allow sharing with groups
- Restrict users to only share with users in their groups
- Exclude groups from sharing

I don't know if it is possible to check for these settings, but if this would be a solution for you, I'd check this and try to fix it that way.
What's your opinion?

**Comment by scroom** [comment]
Yes teachers and students are in different groups (in fact the situation in real life is emulated - teachers are not part of classes or courses but they are teaching them).

So your solution seems to fit this usecase. Would be really cool if we could use the polls app for a lot of use cases in the whole school (nearly 900 users).

**Comment by v1r0x** [comment]
Found this [method(s)](https://doc.owncloud.org/api/classes/OCP.Share.IManager.html#method_allowGroupSharing) in the API. Looks like I can check for the first two points from the list, but I couldn't find anything related to "exclude groups from sharing". But looks promising. :)

**Comment by scroom** [comment]
Cool!
