### ISSUE TITLE
Problem with timezone

### ISSUE THREAD

**Issue by darootler** [v1r0x/polls#53]
Hi!

There seems to be a problem with the timezone.

I am able to reproduce the problem with the following steps:

1.) Create a poll and set date/times to let's say 20:00 o'clock:

![edf8062c-04d7-11e6-8a73-d00de9e29389](https://cloud.githubusercontent.com/assets/11849583/14608021/607e4092-0584-11e6-95b3-fce844f45765.png)

2.) Visit the poll and check date/times:

![32208cb6-04d8-11e6-8b32-9ef00b3aaf7d](https://cloud.githubusercontent.com/assets/11849583/14608038/6c948b84-0584-11e6-8b1b-91818c7c4909.png)

The apache timezone is set to Europe/Vienna.

If you need more information let me know.

Regards
Richard

**Comment by stonerl** [comment]
@darootler what is your timezone-setting in php.ini?

**Comment by darootler** [comment]
Hi,

the php timzone is set to Europe/Vienna.

![image](https://cloud.githubusercontent.com/assets/11849583/14699138/57e3536a-0795-11e6-936a-aba7b6241351.png)

Regards
Richard
