### ISSUE TITLE
Link in polls wrong

### ISSUE THREAD

**Issue by darootler** [v1r0x/polls#56]
Hi,

here is the screenshot:

![image](https://cloud.githubusercontent.com/assets/11849583/14793561/1e9b3350-0b20-11e6-89dc-558f3e3f9212.png)

The Parameter 'overwrite.cli.url' in owncloud/config/config.php is set to 'https://server.XXXXX.biz/owncloud'

Seems that "/owncloud" is too much in the URL.

If you need more information please let me know.

Regards
Richard

**Comment by v1r0x** [comment]
I'll have a look at it, thanks for the report.
