### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by mcorteel** [v1r0x/polls#58]
The colors of the poll header and footer are confusing. First of all, this: 
![spectacle p30302](https://cloud.githubusercontent.com/assets/6164603/14832889/b3fec056-0bfc-11e6-80dd-a69643f14734.png)
The dates are white on white background.
And second, I used a darker color for the header and footer in my PR to make them stand out from the rest. Now they have the same color as the current row, which is confusing.
I think we should get back to a darker color for the header and footer.

And the vote cells are to bright, they should be darker for accessibility. Right now, the icons don't have a good contrast. We could use black icons instead, but I think white icons on a darker background would look better (as it was in my PR).
![spectacle s30302](https://cloud.githubusercontent.com/assets/6164603/14832994/327cfa9c-0bfd-11e6-92f9-dea71b4ac934.png)

@v1r0x what do you think?

**Comment by v1r0x** [comment]
> The dates are white on white background.

Yes, I forgot to fix the color of the dates.

> And second, I used a darker color for the header and footer in my PR to make them stand out from the rest. Now they have the same color as the current row, which is confusing.
> I think we should get back to a darker color for the header and footer.

I like the brighter color more than the dark one and in your latest commit you had the dark and the bright color which was too much in my opinion. We could use the darker color for hover.

> And the vote cells are to bright, they should be darker for accessibility. Right now, the icons don't have a good contrast. We could use black icons instead, but I think white icons on a darker background would look better (as it was in my PR).

Yes, white icon and bright background is not perfect. Maybe we could remove the icons at all and use more darker colors. Afair the colors in your PR were too dark/unsaturated, so something between our colors would be best.

**Comment by darootler** [comment]
Is there any way for me to quick fix the color of the dates? I am currently using the app (actual branch) "productive" and cannot really use it.

Regards
Richard

**Comment by mcorteel** [comment]
@darootler you can apply the patch in PR #60.

**Comment by darootler** [comment]
Thanky you!

Regards
Richard
