### ISSUE TITLE
comment anonymously

### ISSUE THREAD

**Issue by quizilkend** [v1r0x/polls#62]
Hey,

I created a public poll and distributed the link to some people who do not have access to an owncloud account. However when they tried to add a comment, they were redirected to the owncloud login page.
Is it possible to add a comment anonymously?

Thank you very much,
Sammy

**Comment by v1r0x** [comment]
Will add this to the todos for the next release. Thanks for your comment!

**Comment by quizilkend** [comment]
Fixed with https://github.com/v1r0x/polls/pull/83
