### ISSUE TITLE
internal server error when opening a free text poll as extern or other user than the author

### ISSUE THREAD

**Issue by EyesO** [v1r0x/polls#63]
Hello,
I want to create a public poll with free text option where people have to answer different questions.
I get an internal server error when I try to access the poll created with "free text" option when I am not logged in as author of the poll. Polls with the "date" option work fine instead.

The error message is:

> 
> Interner Serverfehler
> Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.
> Bitte wende Dich an den Serveradministrator, sollte dieser Fehler mehrfach auftreten, und füge Deiner Anfrage die unten stehenden technischen Details bei.
> Weitere Details können im Serverprotokoll gefunden werden.
> Technische Details
>     Entfernte Adresse: [my-temporary-IPv6-address]
>     Anforderungskennung: VzdQVcCoKK4AABuRlmwAAAFP

These are the owncloud logs in admin panel:

>Error 	index 
Exception: {"Exception":"BadFunctionCallException","Message":"dt is not a valid attribute","Code":0,"Trace":"#0 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/public\/appframework\/db\/entity.php(147): OCP\\AppFramework\\Db\\Entity->getter('dt')\n#1 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/apps\/polls\/templates\/goto.tmpl.php(191): OCP\\AppFramework\\Db\\Entity->__call('getDt', Array)\n#2 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/apps\/polls\/templates\/goto.tmpl.php(191): OCA\\Polls\\Db\\ParticipationText->getDt()\n#3 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/template\/base.php(160): include('\/mnt\/webr\/c2\/33...')\n#4 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/template\/base.php(138): OC\\Template\\Base->load('\/mnt\/webr\/c2\/33...')\n#5 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/template.php(211): OC\\Template\\Base->fetchPage()\n#6 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/public\/appframework\/http\/templateresponse.php(156): OC_Template->fetchPage()\n#7 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(112): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#8 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Polls\\Controller\\PageController), 'gotoPoll')\n#9 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('PageController', 'gotoPoll', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/route\/router.php(291): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/polls\/got...')\n#13 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/index.php(39): OC::handleRequest()\n#14 {main}","File":"\/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/public\/appframework\/db\/entity.php","Line":128} 	2016-05-14T16:20:38+00:00
>
>Error 	no app in context 
Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"polls_goto\" as such route does not exist.","Code":0,"Trace":"#0 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/route\/router.php(325): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('polls_goto', Array, false)\n#1 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/urlgenerator.php(65): OC\\Route\\Router->generate('polls_goto', Array)\n#2 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/apps\/polls\/templates\/goto.tmpl.php(75): OC\\URLGenerator->linkToRoute('polls_goto', Array)\n#3 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/template\/base.php(160): include('\/mnt\/webr\/c2\/33...')\n#4 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/template\/base.php(138): OC\\Template\\Base->load('\/mnt\/webr\/c2\/33...')\n#5 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/template.php(211): OC\\Template\\Base->fetchPage()\n#6 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/public\/appframework\/http\/templateresponse.php(156): OC_Template->fetchPage()\n#7 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(112): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#8 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/appframework\/app.php(108): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Polls\\Controller\\PageController), 'gotoPoll')\n#9 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('PageController', 'gotoPoll', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#11 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/private\/route\/router.php(291): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#12 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/apps\/polls\/got...')\n#13 \/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/index.php(39): OC::handleRequest()\n#14 {main}","File":"\/mnt\/webr\/c2\/33\/54595533\/htdocs\/owncloud\/3rdparty\/symfony\/routing\/Symfony\/Component\/Routing\/Generator\/UrlGenerator.php","Line":134} 
> 

Does anybody have a clue what's wrong there?

**Comment by v1r0x** [comment]
Sorry, totally forgot about this issue...Will try to reproduce it and report.

**Comment by EyesO** [comment]
This works fine now, great! Thank you.
But commenting doesn't work right. If I write a comment and push the save button the website directs me to the main page and doesn't save the comment.

**Comment by v1r0x** [comment]
Does this happen only in text polls or date polls as well?
I'll close this issue now, please open a new issue for the comment problems.

**Comment by EyesO** [comment]
I just saw there is already an issue #62 for this.
