### ISSUE TITLE
App acts weird whe langugage is set to de_DE

### ISSUE THREAD

**Issue by stonerl** [v1r0x/polls#65]
When the UI-Langugage is set to Deutsch(Förmlich:Sie) de_DE, the app acts weird. For example it is not possible to select groups or users when creating or editing a poll.

Also sending comments ins polls is broken.

**Comment by v1r0x** [comment]
Works for me. WIth 'Deutsch (Persönlich)' and 'Deutsch (Förmlich: Sie)' as well. Are you on latest master and cleared your cache? `Ctrl+F5` was enough on my computer to reload the updated js file instead of using the cached version. Maybe you have an outdated js file.

> Also sending comments ins polls is broken.
What do you mean by "broken"?

**Comment by stonerl** [comment]
I observed this behavior only on ownCloud 8.2.5 On my 9.0.2 installation everything works as expected...

**Comment by stonerl** [comment]
Weird now it works. I had to clear the assets.

**Comment by v1r0x** [comment]
Glad to hear it works!
