### ISSUE TITLE
Only show users from Group

### ISSUE THREAD

**Issue by stonerl** [v1r0x/polls#67]
When creating a new poll the app currently shows all users and not only the users which are part of the creators group. E.g:

Group1: User 1, User 2
Group2: User 2, User 3

When User 1 creates a poll, only Group 1 is listed but all Users. I don't think that it should be like this. With the current behavior all Users of the server are exposed to the creator. The app should respect the option `Restrict users to only share with users in their groups`.

**Comment by v1r0x** [comment]
You are right. Will tweak this. Either restrict users to users of groups the current user is member of or try to get users based on the share settings (in the admin panel).

**Comment by bodo1987** [comment]
As already mentioned in my pull request, I proposed a solution which only shows users of groups the current user is member of. For me, this seems to be a logic solution. However, I am not sure if this is the intended behavior in all cases. For instance, if you are admin and normal users don't have a group, you probably would like to have them in your list as well.
During writing of this comment, I came to the conclusion that this might not be the optimal solution. Nevertheless, it can serve as a starting point ;)

**Comment by bodo1987** [comment]
OK .... #68 shows always users without any group now 

Looks better for me  

RFC

**Comment by v1r0x** [comment]
Is this fixed for you @stonerl ?

**Comment by stonerl** [comment]
yes
