### ISSUE TITLE
No view is as it should.

### ISSUE THREAD

**Issue by Mannshoch** [v1r0x/polls#70]
my creating of a poll (as it should look like)
![2016-06-09 19_42_18-umfragen - owncloud](https://cloud.githubusercontent.com/assets/7795891/15940184/21e3dbe2-2e7b-11e6-8ded-00b7764abf11.png)

what I see if I open the Poll - (hat to merge three printscreens)
![umfragen - owncloud](https://cloud.githubusercontent.com/assets/7795891/15940201/38ffb620-2e7b-11e6-8423-56019d94e082.png)

What the poll tells me if I edit it.
![2016-06-09 19_43_33-umfragen - owncloud](https://cloud.githubusercontent.com/assets/7795891/15940211/491b1c20-2e7b-11e6-89df-b743fdebe85c.png)

ownCloud 9.0.2 (stable)

If you need some more information, please ask.

**Comment by v1r0x** [comment]
The screenshot looks like you submitted the dates 4 times. Maybe there were some errors or something else which leads to these multiple lines.
Could you create a new poll and check if this still exists?

**Comment by Mannshoch** [comment]
You are right!
If I create a pol the Overview is right. But if I go to edit I see this.
![pol](https://cloud.githubusercontent.com/assets/7795891/15961053/f67d5658-2f02-11e6-873e-bf16ca366f45.png)
If I edit this error the times get duplicated.

**Comment by v1r0x** [comment]
Strange...I'll try to reproduce this bug and hopefully can provide a fix
