### ISSUE TITLE
Ver 0.7.1 does not save votes for free text / date votes are saved correctl

### ISSUE THREAD

**Issue by joergmschulz** [v1r0x/polls#71]
While date votes work perfectly, free text votes can be edited / voted on, but will not be saved:

![image](https://cloud.githubusercontent.com/assets/6523646/15943085/9c825660-2e87-11e6-998e-0fe260b9e656.png)

a quick look at the database shows:
SELECT * FROM `oc_polls_particip_text` WHERE text is NULL LIMIT 0, 25 ;

id | poll_id | text | user_id | type
------------ | ------------- | ------------- | ------------- | ------------- 
41 | 4 | NULL | js |1
42	| 4	| NULL	| js	|0
43	| 4	| NULL	| js	|1
44	| 4	| NULL	| somebody	| 1
45	| 4	| NULL	| somebody	| 0
46	| 4	| NULL	| somebody	| 1 

Using OC 9.0.2, PHP5 on a debian server
Browsers tested: chrome, firefox on OSX

My owncloud.log doesn't show anything significant - where else could I look? 
Do you wish to see an example link?

**Comment by v1r0x** [comment]
Maybe it's an apache error (or whatever your server software is). For apache the log files should be in `/var/log/apache2/error.log`
I'll have a look at it, if I don't find anything a link would be good, but I'll try it on my test machine first.
Thanks for the report!

**Comment by jaeger-sb** [comment]
After having a fluffy view on the source code I suppose to found cause of that error on vote.js. 
On line 37:
`newUserDates.push(parseInt($(this).attr('id')));`
a string cannot be parsed into an int value by using using "free text" option. That's why the "text" field in the database is always null. So I would reccomment to fix line 37 it in a way like:
` var userDate = $(this).attr('id');
	    if(isNaN($(this).attr('id')) == true) 
	    {
		newUserDates.push($(this).attr('id'));
	    }
	    else
	    {
		newUserDates.push(parseInt($(this).attr('id')));
	    }`

**Comment by v1r0x** [comment]
Thanks for looking into it!
Unfortunately, I currently don't have that much time for the app. I'll think I can do something this weekend.

@jaeger-sb If you want you can create a PR with your fix.

**Comment by joergmschulz** [comment]
took the freedom to copy the change of @jaeger-sb . To my knowledge, this helps and doesn't break anything. @v1r0x can you approve the PR?
