### ISSUE TITLE
Doesn't work after upgrade to NextCloud 9.0.53

### ISSUE THREAD

**Issue by kosli** [v1r0x/polls#73]
I migrated my OwnCloud 9.0.4 to NextCloud 9.0.53 today and after enabling the polls plugin again, it doesn't work. When switching to the Polls app i get the following:

` {"Exception":"Symfony\\Component\\Routing\\Exception\\InvalidParameterException","Message":"Parameter \"hash\" for route \"polls.page.goto_poll\" must match \"[^\/]++\" (\"\" given) to generate a corresponding URL.","Code":0,"Trace":"#0 \/var\/www\/clients\/client123\/web234\/web.cloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php(136): Symfony\\Component\\Routing\\Generator\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'polls.page.goto...', 1, Array, Array)\n#1 \/var\/www\/clients\/client123\/web234\/web.cloud\/lib\/private\/route\/router.php(316): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('polls.page.goto...', Array, 1)\n#2 \/var\/www\/clients\/client123\/web234\/web.cloud\/lib\/private\/urlgenerator.php(66): OC\\Route\\Router->generate('polls.page.goto...', Array)\n#3 \/var\/www\/clients\/client123\/web234\/web.cloud\/apps\/polls\/templates\/main.tmpl.php(40): OC\\URLGenerator->linkToRoute('polls.page.goto...', Array)\n#4 \/var\/www\/clients\/client123\/web234\/web.cloud\/lib\/private\/template\/base.php(161): include('\/var\/www\/client...')\n#5 \/var\/www\/clients\/client123\/web234\/web.cloud\/lib\/private\/template\/base.php(139): OC\\Template\\Base->load('\/var\/www\/client...')\n#6 \/var\/www\/clients\/client123\/web234\/web.cloud\/lib\/private\/template.php(222): OC\\Template\\Base->fetchPage()\n#7 \/var\/www\/clients\/client123\/web234\/web.cloud\/lib\/public\/appframework\/http\/templateresponse.php(156): OC_Template->fetchPage()\n#8 \/var\/www\/clients\/client123\/web234\/web.cloud\/lib\/private\/appframework\/http\/dispatcher.php(112): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#9 \/var\/www\/clients\/client123\/web234\/web.cloud\/lib\/private\/appframework\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Polls\\Controller\\PageController), 'index')\n#10 \/var\/www\/clients\/client123\/web234\/web.cloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('PageController', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#11 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#12 \/var\/www\/clients\/client123\/web234\/web.cloud\/lib\/private\/route\/router.php(276): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#13 \/var\/www\/clients\/client123\/web234\/web.cloud\/lib\/base.php(967): OC\\Route\\Router->match('\/apps\/polls\/')\n#14 \/var\/www\/clients\/client123\/web234\/web.cloud\/index.php(39): OC::handleRequest()\n#15 {main}","File":"\/var\/www\/clients\/client123\/web234\/web.cloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php","Line":177}`

**Comment by v1r0x** [comment]
I think we had this bug in the past. Does this occur on the summary page or somewhere else?
Looks like there is something wrong with the hashes in the database. Could you have a look at the oc_polls_* tables and check if there is a `\` in the hash column?

**Comment by kosli** [comment]
this happens when going straight on the "polls" tile in the menu. 
there is only one poll in oc_polls_events and that has a "NULL" hash value. but i think the poll has been deleted, as all other entries have a "poll_id" of "NULL" too. i'll just empty the tables and see if it works.

**Comment by kosli** [comment]
truncating the polls tables (as there was no "valid" poll anymore) helped to solve the problem. i can create and delete new polls now without problems. closing this issue. thanks for the lp

**Comment by v1r0x** [comment]
Glad to hear it's fixed. You're welcome.

**Comment by kosli** [comment]
and another owncloud instance that i migrated to nextcloud hasn't had an issue either with the polls. the existing polls work as expected.
