### ISSUE TITLE
set max version to newer OC

### ISSUE THREAD

**Issue by joergmschulz** [v1r0x/polls#74]
Just activated the polls on my nextcloud  beta 10, works like on OC 9 and NC 9.52 / text polls not possible, but date polls seem to work alright.
So, version might be bumped....

**Comment by v1r0x** [comment]
I switched from oc to nc and I'm still on 9.0.52 I think. Don't know if it still works in OC 9.1. Do you have the possibility to check this?
If someone can confirm that it works, I'll bump the max-version to 9.1

**Comment by joergmschulz** [comment]
Well, my most recent OC is 9.0; polls app works fine on NC 10 beta when the PR 76 is applied.
