### ISSUE TITLE
"App can't be installed because the version in info.xml/version is not the same as the version reported from the app store"

### ISSUE THREAD

**Issue by RealRancor** [v1r0x/polls#91]
Hi,

seems you forgot to update the appinfo/info.xml with version 0.7.2:

https://github.com/v1r0x/polls/blob/0.7.2/appinfo/info.xml#L6

Btw. thanks for still updating / working on this app.

**Comment by v1r0x** [comment]
Happens every release... :smile: Thanks for the info

**Comment by RealRancor** [comment]
Thanks, works now as expected :+1:
