### ISSUE TITLE
UI/Design broken in release 0.7.2

### ISSUE THREAD

**Issue by nextgen-networks** [v1r0x/polls#92]
Installed new Version 0.7.2 - edited the version string in info.xml to activate the app.

Afterwards the design seemed to be gone - looks somewhat crappy.

Thanks for maintaining this app!

**Comment by v1r0x** [comment]
Did you try to force a reload with `Ctrl+F5` (at least in firefox)?
If this doesn't work, could you please provide a log file and your oc/nc version?

**Comment by nextgen-networks** [comment]
I'll test it with your updated release and send an feedback.

My test-scenario:
- Apache Webserver
- PHP 7.0.12
- Redis cache  (flushed cache - to prevent any side effects caused from it)
- Chrome Browser 54.0.2840.71 (with cache flushed also)

**Comment by nextgen-networks** [comment]
OK after rerelease all problems are gone - UI works as expected.
This issue can be closed.

Thanks for your cool app!

**Comment by v1r0x** [comment]
Great!

Thanks :smiley:

**Comment by RealRancor** [comment]
Confirmed that this issue didn't shown up on 0.7.2 with current oC 9.0.5
