### ISSUE TITLE
Time zone issue?

### ISSUE THREAD

**Issue by poVoq** [v1r0x/polls#97]
With 0.7.2 there seems to be a time zone issue.

I select when creating a event poll times 9:00 10:00 etc. but in the actual poll they show up as 1:00, 2:00 etc.

Our server has a timezone set of UTC+8 (Manila) so it is likely that the app doesn't take this into account properly.

This might be related to some recent timezone issues in Owncloud/nextcloud also, but thanks for looking into it.

**Comment by v1r0x** [comment]
I'll have a look at it this weekend, thanks for the report

**Comment by uyekt** [comment]
Same Problem here. I entered a poll for 19:30 and 19:45 but it shows up as 18:30 and 18:45.
It is saved in the db in the table polls_dts with 18:30 and 18:45. 
Our server has a timezone set of UTC+2 (Berlin). 
Hope it might help.

**Comment by v1r0x** [comment]
I had a look at the code and created some polls on my test machine and I couldn't find a bug.
[This ](https://github.com/v1r0x/polls/blob/master/controller/pagecontroller.php#L343-L353) is the part in the code, where I add the user's timezone to the dates (after they created the poll), if no timezone is set, UTC is used.
From what I found in issues in core, it is not possible for users to modify their timezone. I don't know how oc determines the "correct" timezone for users. You could have a look at the database and check the values for `select * from oc_preferences where configkey = 'timezone'`. You could try to modify these values and create new polls and check if you have other results (and check if the values in the db are stored even after the user relogins).

**Comment by poVoq** [comment]
This might be related: https://forum.owncloud.org/viewtopic.php?t=22616
Will check tomorrow if I can alter the time-zone of our Nextcloud.

**Comment by poVoq** [comment]
Setting the default timezone in the /lib/base.php seems to have fixed it. Maybe something to mention in the description of the app? However since this setting is nowhere exposed in the Owncloud/Nextcloud GUI, nor part of the normal installation process it seems a bit like a workaround and not really intended like that.

**Comment by v1r0x** [comment]
Have you tried to set it for a specific user mentioned in my comment?
Setting it in `/lib/base.php` modifies the server's timezone. Thus, you only get correct results for users which are in the same timezone (as the server).
I think the main problem is, that oc/nc provides the user's timezone as value in the database, but the user has no chance to modify it. But you are right, if it can only be set this way, it should be mentioned in the app's description.

**Comment by poVoq** [comment]
I don't want to mess around with the database in our production system and since we don't have users outside this timezone it's not an issue for us. But you are right, it isn't really an option for all use-cases.

Wouldn't it be possible to do the time conversion client side only? I.e. server side everything is stored as UTC as that's the default settings of Owncloud that apparently isn't supposed to be changed, and then the browser is asked to add the timezone based on the client settings when displaying the time?

**Comment by v1r0x** [comment]
I thought this would lead to wrong results, but after thinking about it, it seems like a good solution.
I'll add this as todo for the next release.
Thanks!

**Comment by joergmschulz** [comment]
I see you fiexed many things today; does it make sense to download master to a test system and play around a bit - or will you create a beta release?

**Comment by v1r0x** [comment]
I try to release 0.7.3 in the next days/weeks. But you could definitely try the current master to check if it really works.

**Comment by joergmschulz** [comment]
Will there be a version / branch that works on NC 12? The master I installed a minute ago doesn’t.

**Comment by v1r0x** [comment]
All my systems are on NC11, but I setup a second testing VM with NC12. Have you tried to increase the `max-version` in `appinfo/info.xml` from `11` to `12`?

**Comment by joergmschulz** [comment]
Yes - and I got weird error messages in the browser console. Possibly an outdated api call? Do you want me to reproduce and document here, or will you do it anyway?

**Comment by v1r0x** [comment]
Best would be if you open a new issue (e.g. NC12 compatibility) and add your errors there.

**Comment by joergmschulz** [comment]
done so. It's no good to abuse this closed thread anyway, sorry.
